
-- 1. Create Products Table
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null default 0,
  category text,
  image_color text default 'bg-indigo-500/20',
  image_url text, 
  gallery text[],
  user_id uuid references auth.users default auth.uid()
);

-- 2. Create Posts Table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  platform text not null,
  content_type text not null,
  caption text,
  image_url text, 
  video_url text,
  status text default 'scheduled',
  scheduled_date timestamp with time zone,
  product_id bigint references products(id),
  user_id uuid references auth.users default auth.uid()
);

-- 3. Create Inbox Messages Table
create table if not exists public.inbox_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users default auth.uid(),
  platform text not null, -- 'facebook', 'instagram', 'whatsapp'
  external_id text, -- Message ID from Meta
  sender_id text not null, -- PSID or Phone Number
  sender_name text, -- Name of the user (if available)
  avatar_url text, -- Profile pic url (if available)
  text text, -- The message content
  is_from_me boolean default false, -- True if sent by us/AI
  status text default 'unread', -- 'unread', 'read', 'archived'
  ai_response_status text default 'pending', -- 'pending', 'replied', 'manual_control', 'failed'
  conversation_id text, -- Optional: to group threads manually if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create User Settings Table
create table if not exists public.user_settings (
  user_id uuid references auth.users not null primary key,
  gemini_api_key text,
  meta_app_id text,
  meta_app_secret text, 
  meta_access_token text,
  meta_page_id text,
  meta_page_name text,
  meta_page_access_token text,
  meta_instagram_id text,
  tiktok_client_key text,
  tiktok_client_secret text,
  ai_knowledge_base text,
  brand_voice_presets jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Enable Row Level Security (RLS)
alter table public.posts enable row level security;
alter table public.products enable row level security;
alter table public.inbox_messages enable row level security;
alter table public.user_settings enable row level security;

-- 6. Create Policies (User Scoped Access)

-- Products
drop policy if exists "Users can view own products" on products;
create policy "Users can view own products" on products for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own products" on products;
create policy "Users can insert own products" on products for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own products" on products;
create policy "Users can update own products" on products for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own products" on products;
create policy "Users can delete own products" on products for delete using (auth.uid() = user_id);

-- Posts
drop policy if exists "Users can view own posts" on posts;
create policy "Users can view own posts" on posts for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own posts" on posts;
create policy "Users can insert own posts" on posts for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own posts" on posts;
create policy "Users can update own posts" on posts for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own posts" on posts;
create policy "Users can delete own posts" on posts for delete using (auth.uid() = user_id);

-- Inbox Messages
drop policy if exists "Users can view own messages" on inbox_messages;
create policy "Users can view own messages" on inbox_messages for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own messages" on inbox_messages;
create policy "Users can insert own messages" on inbox_messages for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own messages" on inbox_messages;
create policy "Users can update own messages" on inbox_messages for update using (auth.uid() = user_id);

-- User Settings
drop policy if exists "Users can view their own settings" on user_settings;
create policy "Users can view their own settings" on user_settings for select using (auth.uid() = user_id);

drop policy if exists "Users can update their own settings" on user_settings;
create policy "Users can update their own settings" on user_settings for update using (auth.uid() = user_id);

drop policy if exists "Users can insert their own settings" on user_settings;
create policy "Users can insert their own settings" on user_settings for insert with check (auth.uid() = user_id);


-- 7. Trigger to automatically create User Settings on Signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.user_settings (user_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 8. Storage Bucket Setup
insert into storage.buckets (id, name, public)
values ('viral-boost-assets', 'viral-boost-assets', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'viral-boost-assets' );

create policy "Allow Uploads (Auth)"
  on storage.objects for insert
  with check ( bucket_id = 'viral-boost-assets' and auth.role() = 'authenticated' );
