-- Create the Inbox Messages table
create table inbox_messages (
  id bigint generated by default as identity primary key,
  platform text not null, -- 'facebook', 'instagram', 'whatsapp'
  external_id text, -- Message ID from Meta
  sender_id text not null, -- PSID or Phone Number
  sender_name text, -- Name of the user (if available)
  avatar_url text, -- Profile pic url (if available)
  text text, -- The message content
  is_from_me boolean default false, -- True if sent by us/AI
  status text default 'unread', -- 'unread', 'read', 'archived'
  ai_response_status text default 'pending', -- 'pending', 'replied', 'manual_control', 'failed'
  conversation_id text, -- Optional: to group threads manually if needed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table inbox_messages enable row level security;

-- Policy to allow Read/Write (Adjust for production!)
create policy "Allow all access" on inbox_messages for all using (true) with check (true);

-- Create a realtime publication so Electron can listen
drop publication if exists supabase_realtime;
create publication supabase_realtime for table inbox_messages;
