-- Create Products Table
create table products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  category text,
  image_color text default 'bg-indigo-500/20',
  image_url text, -- Added for persistence
  gallery text[]  -- Added for persistence
);

-- Basic RLS Policies (Open for now for ease of prototype)
alter table products enable row level security;
create policy "Public products are viewable by everyone." on products for select using (true);
create policy "Public products are insertable by everyone." on products for insert with check (true);
create policy "Public products are updatable by everyone." on products for update using (true);
create policy "Public products are deletable by everyone." on products for delete using (true);

-- Create Scheduled Posts Table
create table posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  platform text not null,
  content_type text not null,
  caption text,
  image_url text, -- For future use
  video_url text, -- For future use
  status text default 'scheduled',
  scheduled_date timestamp with time zone,
  product_id bigint references products(id)
);

alter table posts enable row level security;
create policy "Public posts are viewable by everyone." on posts for select using (true);
create policy "Public posts are insertable by everyone." on posts for insert with check (true);

-- Seed Data (Optional)
insert into products (name, price, category, image_color) values
('Zapatillas Urban Flow', 89.99, 'Moda', 'bg-orange-500/20'),
('Auriculares NoiseOff', 129.99, 'Tech', 'bg-indigo-500/20'),
('Serum Glow Skin', 34.50, 'Belleza', 'bg-pink-500/20');
