import React, { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { Download, Share2, Sparkles, CheckCircle, Copy } from 'lucide-react';

const BriefExport = ({ strategy, product, tone }) => {
  const cardRef = useRef(null);
  const [downloading, setDownloading] = useState(false);

  const handleDownload = async () => {
    if (!cardRef.current) return;
    setDownloading(true);
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 2, // High resolution
        backgroundColor: '#0f172a', // Match theme
        useCORS: true // Allow loading cross-origin images
      });
      
      const image = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = image;
      link.download = `Estrategia-Viral-${product?.name || 'V1'}.png`;
      link.click();
    } catch (err) {
      console.error("Error generating image:", err);
      alert("No se pudo generar la imagen. Intenta de nuevo.");
    } finally {
      setDownloading(false);
    }
  };

  if (!strategy) return null;

  return (
    <div className="mt-4">
      {/* Controls */}
      <div className="flex justify-between items-center mb-3">
        <label className="text-xs font-bold text-slate-500 uppercase">
           Brief Visual
        </label>
        <button 
          onClick={handleDownload}
          disabled={downloading}
          className="text-xs bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1.5 rounded-lg font-bold flex items-center gap-1.5 transition-all disabled:opacity-50"
        >
           {downloading ? 'Generando...' : <><Download size={12} /> Descargar Ficha</>}
        </button>
      </div>

      {/* The Printable Card (Hidden from main layout flow via scroll or modal usually, but here embedded) */}
      <div className="overflow-x-auto pb-4 -mx-2 px-2">
      <div 
        ref={cardRef}
        className="w-[400px] bg-slate-900 border border-slate-700 p-6 rounded-2xl shadow-2xl relative overflow-hidden"
      >
        {/* Background Accents */}
        <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl -mr-10 -mt-10"></div>
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-purple-500/10 rounded-full blur-2xl -ml-5 -mb-5"></div>

        {/* Header */}
        <div className="flex items-center justify-between mb-6 relative z-10">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-linear-to-tr from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <Sparkles className="text-white" size={16} />
            </div>
            <div>
              <h3 className="font-bold text-white text-sm leading-tight">Viral Strategy</h3>
              <p className="text-[10px] text-indigo-300 font-medium">Generated by Yaminator AI</p>
            </div>
          </div>
          <div className="text-right">
             <span className="text-[10px] text-slate-500 block">FECHA</span>
             <span className="text-xs font-bold text-slate-300">{new Date().toLocaleDateString()}</span>
          </div>
        </div>

        {/* Product Info */}
        <div className="flex gap-4 mb-6 relative z-10">
           <div className="w-20 h-20 bg-slate-800 rounded-xl overflow-hidden border border-slate-700 shadow-lg shrink-0">
              {product?.image_url ? (
                <img src={product.image_url} className="w-full h-full object-cover" alt="Product" crossOrigin="anonymous" />
              ) : (
                <div className="w-full h-full flex items-center justify-center text-slate-600 font-bold text-xs">NO IMG</div>
              )}
           </div>
           <div className="flex-1">
              <h4 className="font-bold text-white text-lg leading-tight mb-1">{product?.name || 'Producto Sin Nombre'}</h4>
              <div className="flex flex-wrap gap-2 mt-2">
                 <span className="px-2 py-0.5 rounded bg-slate-800 border border-slate-700 text-[10px] text-slate-300 uppercase font-bold">
                    {tone || 'Professional'} Tone
                 </span>
                 <span className="px-2 py-0.5 rounded bg-emerald-900/30 border border-emerald-800 text-[10px] text-emerald-400 uppercase font-bold">
                    Viral Score: High
                 </span>
              </div>
           </div>
        </div>

        {/* Strategy Content */}
        <div className="space-y-4 relative z-10">
           
           {/* Angle */}
           <div className="bg-slate-800/50 p-3 rounded-xl border border-slate-700/50">
              <p className="text-[10px] text-slate-500 uppercase font-bold mb-1 flex items-center gap-1">
                 <CheckCircle size={10} className="text-indigo-400" /> Ángulo Creativo
              </p>
              <p className="text-sm text-slate-200 font-medium leading-relaxed">
                 {strategy.angle || "Enfoque basado en beneficios directos y urgencia."}
              </p>
           </div>

           {/* Hook */}
           <div className="bg-linear-to-r from-indigo-900/20 to-purple-900/20 p-3 rounded-xl border border-indigo-500/20">
              <p className="text-[10px] text-indigo-300 uppercase font-bold mb-1 flex items-center gap-1">
                 <Sparkles size={10} /> Hook Principal (3s)
              </p>
              <p className="text-lg text-white font-bold leading-tight">
                 "{strategy.hook || '¡Detente! Tienes que ver esto.'}"
              </p>
           </div>

           {/* CTAs */}
           <div className="grid grid-cols-2 gap-3">
              <div className="bg-slate-800/30 p-2 rounded-lg border border-slate-700/30">
                 <span className="text-[9px] text-slate-500 block mb-1">CALL TO ACTION</span>
                 <span className="text-xs text-slate-300 font-medium">{strategy.cta || "Link en Bio"}</span>
              </div>
              <div className="bg-slate-800/30 p-2 rounded-lg border border-slate-700/30">
                 <span className="text-[9px] text-slate-500 block mb-1">FORMATO</span>
                 <span className="text-xs text-slate-300 font-medium">Reels / TikTok (9:16)</span>
              </div>
           </div>

        </div>

        {/* Footer */}
        <div className="mt-6 pt-4 border-t border-slate-800 text-center relative z-10">
           <p className="text-[9px] text-slate-600 font-medium tracking-widest uppercase">CONFIDENTIAL • INTERNAL USE ONLY</p>
        </div>

      </div>
      </div>
      <p className="text-[10px] text-slate-500 text-center mt-2 italic">
         Previsualización (El descargable será de alta calidad)
      </p>
    </div>
  );
};

export default BriefExport;
